import { createClient } from "@supabase/supabase-js";
import { supabaseUrl } from "@/lib/auth/env";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

/** Private file storage. Objects are only ever served after an application-level authorization check. */
export interface StorageService {
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  remove(key: string): Promise<void>;
  /** Either a short-lived signed URL to redirect to, or the bytes to stream. */
  read(key: string): Promise<{ redirectUrl: string } | { bytes: Uint8Array }>;
}

const BUCKET = "evidence";

class SupabaseStorage implements StorageService {
  private client = createClient(supabaseUrl(), process.env.SUPABASE_SERVICE_ROLE_KEY!, {
    auth: { persistSession: false },
  });

  async put(key: string, bytes: Uint8Array, contentType: string) {
    const { error } = await this.client.storage
      .from(BUCKET)
      .upload(key, bytes, { contentType, upsert: false });
    if (error) throw new Error(`storage upload failed: ${error.message}`);
  }

  async remove(key: string) {
    const { error } = await this.client.storage.from(BUCKET).remove([key]);
    if (error) throw new Error(`storage remove failed: ${error.message}`);
  }

  async read(key: string) {
    const { data, error } = await this.client.storage.from(BUCKET).createSignedUrl(key, 60);
    if (error || !data) throw new Error(`storage sign failed: ${error?.message}`);
    return { redirectUrl: data.signedUrl };
  }
}

/** Development fallback: files in ./.uploads (git-ignored). Never used in production. */
class LocalStorage implements StorageService {
  private root = path.join(process.cwd(), ".uploads");

  private resolve(key: string) {
    const full = path.resolve(this.root, key);
    // Defense in depth against path traversal, on top of server-generated keys.
    if (!full.startsWith(this.root + path.sep)) throw new Error("invalid storage key");
    return full;
  }

  async put(key: string, bytes: Uint8Array) {
    const file = this.resolve(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, bytes);
  }

  async remove(key: string) {
    await unlink(this.resolve(key)).catch(() => undefined);
  }

  async read(key: string) {
    return { bytes: new Uint8Array(await readFile(this.resolve(key))) };
  }
}

export function getStorage(): StorageService {
  if (process.env.SUPABASE_SERVICE_ROLE_KEY && process.env.NEXT_PUBLIC_SUPABASE_URL)
    return new SupabaseStorage();
  if (process.env.NODE_ENV === "production") throw new Error("Storage is not configured");
  return new LocalStorage();
}

/** Object key generated by the server: the user's file name never reaches the storage path. */
export const newStorageKey = (profileId: string, ext: string) => `${profileId}/${randomUUID()}.${ext}`;
