export const EVIDENCE_TYPES = [
  "PROJECT",
  "CERTIFICATION",
  "DOCUMENT",
  "SCREENSHOT",
  "LINK",
  "REPOSITORY",
  "PORTFOLIO",
  "ASSESSMENT",
  "RECOMMENDATION",
  "EXPERIENCE",
] as const;
export type EvidenceType = (typeof EVIDENCE_TYPES)[number];

export const EVIDENCE_TYPE_LABELS: Record<EvidenceType, string> = {
  PROJECT: "Projet",
  CERTIFICATION: "Certification",
  DOCUMENT: "Document",
  SCREENSHOT: "Capture d'écran",
  LINK: "Lien",
  REPOSITORY: "Dépôt GitHub",
  PORTFOLIO: "Portfolio",
  ASSESSMENT: "Évaluation",
  RECOMMENDATION: "Recommandation",
  EXPERIENCE: "Expérience professionnelle",
};

/** Types the user can create by hand. The others are generated by the platform (assessments, recommendations). */
export const USER_EVIDENCE_TYPES = [
  "PROJECT",
  "CERTIFICATION",
  "DOCUMENT",
  "SCREENSHOT",
  "LINK",
  "REPOSITORY",
  "PORTFOLIO",
  "EXPERIENCE",
] as const satisfies readonly EvidenceType[];

/** Types that must carry an uploaded file / an external URL. */
export const FILE_EVIDENCE_TYPES: readonly EvidenceType[] = ["DOCUMENT", "SCREENSHOT"];
export const URL_EVIDENCE_TYPES: readonly EvidenceType[] = ["LINK", "REPOSITORY", "PORTFOLIO"];

export type EvidenceStatus = "UNVERIFIED" | "PENDING" | "VERIFIED";

export const EVIDENCE_STATUS_LABELS: Record<EvidenceStatus, string> = {
  UNVERIFIED: "Non vérifiée",
  PENDING: "En cours de vérification",
  VERIFIED: "Vérifiée",
};

export interface EvidenceDTO {
  id: string;
  talentSkillId: string;
  skillName: string;
  projectId: string | null;
  type: EvidenceType;
  title: string;
  description: string | null;
  url: string | null;
  /** Original file name, for display only. The storage key is never exposed. */
  fileName: string | null;
  mimeType: string | null;
  sizeBytes: number | null;
  hasFile: boolean;
  status: EvidenceStatus;
  createdAt: string;
}

/** What the repository persists. `filePath` is the storage key, server-side only. */
export interface NewEvidence {
  talentSkillId: string;
  projectId?: string;
  type: EvidenceType;
  title: string;
  description?: string;
  url?: string;
  file?: { path: string; name: string; mimeType: string; sizeBytes: number };
}
