import type { OpportunityDTO } from "@/types/opportunity";

type Seed = Omit<OpportunityDTO, "id" | "publishedAt" | "description" | "applyUrl" | "companyLabel"> & {
  daysAgo: number;
  companyLabel?: string;
};

const o = (
  company: string,
  title: string,
  kind: string,
  region: string,
  location: string,
  workMode: string | null,
  commitment: string | null,
  domain: string,
  level: string,
  skills: string[],
  daysAgo: number,
  companyLabel?: string,
): Seed => ({
  company,
  companyLabel,
  title,
  kind,
  region,
  location,
  workMode,
  commitment,
  domain,
  level,
  skills,
  daysAgo,
});

const ABIDJAN = "Abidjan, Côte d'Ivoire";

/** Fictitious job board: the first six are the ones shown on the mockup. */
const SEEDS: Seed[] = [
  o(
    "AGL",
    "Développeur Power Platform",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Power Apps", "Power Automate", "Dataverse"],
    2,
  ),
  o(
    "Microsoft",
    "Solution Architect (Power Platform)",
    "EMPLOI",
    "REMOTE",
    "Remote (Worldwide)",
    "REMOTE",
    "Temps plein",
    "Tech & Digital",
    "SENIOR",
    ["Power Platform", "Azure", "AI"],
    5,
  ),
  o(
    "SEHIN GROUP",
    "Stagiaire Développeur",
    "STAGE",
    "CI",
    ABIDJAN,
    null,
    "Stage (6 mois)",
    "Tech & Digital",
    "BEGINNER",
    ["React", "Power Apps", "SharePoint"],
    7,
  ),
  o(
    "Upwork",
    "Développement d'une app métier",
    "FREELANCE",
    "REMOTE",
    "Remote",
    null,
    "Mission (1-3 mois)",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Power Apps", "API", "SQL"],
    1,
  ),
  o(
    "Banque Atlantique",
    "Consultant Data & BI",
    "PROJET",
    "CI",
    ABIDJAN,
    null,
    "Mission",
    "Data & IA",
    "INTERMEDIATE",
    ["Power BI", "Dataverse", "Data Analysis"],
    3,
  ),
  o(
    "Orange CI",
    "Product Owner Digital",
    "EMPLOI",
    "AFRICA",
    "Côte d'Ivoire / Afrique de l'Ouest",
    null,
    "CDI",
    "Gestion & Business",
    "SENIOR",
    ["Gestion de projet", "Agile", "Communication"],
    7,
    "Orange Digital Center",
  ),

  o(
    "AGL",
    "Chef de projet digital",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Gestion & Business",
    "SENIOR",
    ["Gestion de projet", "Agile", "Leadership"],
    9,
  ),
  o(
    "AGL",
    "Analyste Business Intelligence",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Data & IA",
    "INTERMEDIATE",
    ["Power BI", "SQL", "Data Analysis"],
    12,
  ),
  o(
    "AGL",
    "Consultant Dataverse",
    "PROJET",
    "CI",
    ABIDJAN,
    null,
    "Mission (3-6 mois)",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Dataverse", "Power Apps", "Power Automate"],
    14,
  ),
  o(
    "AGL",
    "Développeur Full Stack",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    ["React", "Node.js", "SQL"],
    15,
  ),
  o(
    "AGL",
    "Product Owner",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Gestion & Business",
    "SENIOR",
    ["Agile", "Gestion de projet", "Communication"],
    18,
  ),
  o(
    "AGL",
    "Data Engineer",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Data & IA",
    "SENIOR",
    ["Python", "SQL", "Azure"],
    20,
  ),
  o(
    "AGL",
    "Administrateur SharePoint",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDD",
    "Cloud & Infrastructure",
    "INTERMEDIATE",
    ["SharePoint", "Microsoft 365", "Power Automate"],
    22,
  ),
  o(
    "AGL",
    "Architecte de solutions",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "SENIOR",
    ["Azure", "Power Platform", "API"],
    25,
  ),
  o(
    "AGL",
    "Stagiaire Power Apps",
    "STAGE",
    "CI",
    ABIDJAN,
    null,
    "Stage (4 mois)",
    "Tech & Digital",
    "BEGINNER",
    ["Power Apps", "Dataverse"],
    26,
  ),
  o(
    "AGL",
    "Support applicatif niveau 2",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Cloud & Infrastructure",
    "BEGINNER",
    ["Support IT", "SQL", "Communication"],
    29,
  ),
  o(
    "AGL",
    "Formateur Power Platform",
    "FREELANCE",
    "CI",
    ABIDJAN,
    null,
    "Mission (1 mois)",
    "Tech & Digital",
    "SENIOR",
    ["Power Apps", "Power Automate", "Communication"],
    31,
  ),

  o(
    "Microsoft",
    "Cloud Solution Architect",
    "EMPLOI",
    "EUROPE",
    "Paris, France",
    "HYBRID",
    "Temps plein",
    "Cloud & Infrastructure",
    "SENIOR",
    ["Azure", "Cloud", "Architecture"],
    11,
  ),
  o(
    "Microsoft",
    "Customer Success Manager",
    "EMPLOI",
    "EUROPE",
    "Dublin, Irlande",
    "HYBRID",
    "Temps plein",
    "Gestion & Business",
    "INTERMEDIATE",
    ["Communication", "Power Platform", "Gestion de projet"],
    10,
  ),
  o(
    "Microsoft",
    "Technical Trainer Power Platform",
    "FREELANCE",
    "REMOTE",
    "Remote (Europe)",
    null,
    "Mission (1-3 mois)",
    "Tech & Digital",
    "SENIOR",
    ["Power Apps", "Power BI", "Communication"],
    13,
  ),
  o(
    "Microsoft",
    "Data & AI Specialist",
    "EMPLOI",
    "NORTH_AMERICA",
    "Redmond, États-Unis",
    "ONSITE",
    "Temps plein",
    "Data & IA",
    "SENIOR",
    ["AI", "Azure", "Python"],
    16,
  ),
  o(
    "Microsoft",
    "Program Manager Power Apps",
    "EMPLOI",
    "NORTH_AMERICA",
    "Seattle, États-Unis",
    "HYBRID",
    "Temps plein",
    "Gestion & Business",
    "SENIOR",
    ["Power Apps", "Gestion de projet", "Leadership"],
    19,
  ),
  o(
    "Microsoft",
    "Support Engineer Dynamics 365",
    "EMPLOI",
    "AFRICA",
    "Casablanca, Maroc",
    "ONSITE",
    "CDI",
    "Cloud & Infrastructure",
    "BEGINNER",
    ["Dynamics 365", "Support IT", "Dataverse"],
    21,
  ),
  o(
    "Microsoft",
    "Partner Development Manager",
    "EMPLOI",
    "AFRICA",
    "Johannesburg, Afrique du Sud",
    "HYBRID",
    "Temps plein",
    "Gestion & Business",
    "SENIOR",
    ["Communication", "Leadership", "Power Platform"],
    27,
  ),

  o(
    "Orange CI",
    "Développeur Mobile",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    ["React", "API", "SQL"],
    8,
    "Orange Digital Center",
  ),
  o(
    "Orange CI",
    "Data Analyst",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Data & IA",
    "INTERMEDIATE",
    ["Power BI", "SQL", "Python"],
    11,
  ),
  o(
    "Orange CI",
    "Chef de projet réseau",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Cloud & Infrastructure",
    "SENIOR",
    ["Réseau", "Gestion de projet", "Leadership"],
    17,
  ),
  o(
    "Orange CI",
    "Stagiaire Marketing digital",
    "STAGE",
    "CI",
    ABIDJAN,
    null,
    "Stage (6 mois)",
    "Autres",
    "BEGINNER",
    ["Communication", "Analyse fonctionnelle"],
    23,
  ),
  o(
    "Orange CI",
    "Ingénieur Cloud",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Cloud & Infrastructure",
    "INTERMEDIATE",
    ["Azure", "Cloud", "Réseau"],
    28,
  ),

  o(
    "SEHIN GROUP",
    "Développeur React",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    ["React", "TypeScript", "Node.js"],
    10,
  ),
  o(
    "SEHIN GROUP",
    "Consultant Power Automate",
    "PROJET",
    "CI",
    ABIDJAN,
    null,
    "Mission (2 mois)",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Power Automate", "SharePoint", "API"],
    12,
  ),
  o(
    "SEHIN GROUP",
    "Alternant Chef de projet",
    "ALTERNANCE",
    "CI",
    ABIDJAN,
    null,
    "Alternance (12 mois)",
    "Gestion & Business",
    "BEGINNER",
    ["Gestion de projet", "Agile", "Communication"],
    20,
  ),
  o(
    "SEHIN GROUP",
    "Designer UX/UI",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDD",
    "Autres",
    "INTERMEDIATE",
    ["Design", "UI/UX", "Communication"],
    30,
  ),

  o(
    "Banque Atlantique",
    "Analyste risques",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Gestion & Business",
    "INTERMEDIATE",
    ["Analyse fonctionnelle", "SQL", "Communication"],
    9,
  ),
  o(
    "Banque Atlantique",
    "Développeur Power Apps",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Power Apps", "Dataverse", "Power Automate"],
    15,
  ),
  o(
    "Banque Atlantique",
    "Chef de projet transformation digitale",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Gestion & Business",
    "SENIOR",
    ["Gestion de projet", "Leadership", "Agile"],
    24,
  ),
];

const describe = (s: Seed) =>
  `${s.companyLabel ?? s.company} recherche un(e) ${s.title} (${s.location}). ` +
  `Vous interviendrez sur des sujets liés à ${s.skills.slice(0, 3).join(", ")} au sein d'une équipe pluridisciplinaire, ` +
  `avec des objectifs clairs et un vrai impact sur les utilisateurs.\n\n` +
  `Compétences recherchées : ${s.skills.join(", ")}.\n` +
  `Type de contrat : ${s.commitment ?? "à définir"}.`;

const DAY_MS = 86_400_000;

/** Offers with publication dates relative to `now`, so "il y a 2 jours" stays true whenever the demo runs. */
export function buildDemoOpportunities(now = new Date()): Omit<OpportunityDTO, "id">[] {
  return SEEDS.map(({ daysAgo, ...s }) => ({
    ...s,
    companyLabel: s.companyLabel ?? null,
    description: describe({ daysAgo, ...s }),
    applyUrl: null,
    publishedAt: new Date(now.getTime() - daysAgo * DAY_MS).toISOString(),
  }));
}
