import type { OpportunityDTO } from "@/types/opportunity";

/** The fields written by hand for each demo offer; the rest of the sheet is generated. */
type Seed = Pick<
  OpportunityDTO,
  | "company"
  | "title"
  | "kind"
  | "region"
  | "location"
  | "workMode"
  | "commitment"
  | "domain"
  | "level"
  | "skills"
> & { daysAgo: number; companyLabel?: string };

const o = (
  company: string,
  title: string,
  kind: string,
  region: string,
  location: string,
  workMode: string | null,
  commitment: string | null,
  domain: string,
  level: string,
  skills: string[],
  daysAgo: number,
  companyLabel?: string,
): Seed => ({
  company,
  companyLabel,
  title,
  kind,
  region,
  location,
  workMode,
  commitment,
  domain,
  level,
  skills,
  daysAgo,
});

const ABIDJAN = "Abidjan, Côte d'Ivoire";

/** Fictitious job board: the first six are the ones shown on the list mockup. */
const SEEDS: Seed[] = [
  o(
    "AGL",
    "Développeur Power Platform",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    [
      "Power Apps",
      "Power Automate",
      "Dataverse",
      "Power BI",
      "SharePoint",
      "API",
      "Analyse fonctionnelle",
      "Gestion de projet",
      "ALM",
      "Git",
      "UX/UI",
      "Agilité",
    ],
    2,
  ),
  o(
    "Microsoft",
    "Solution Architect (Power Platform)",
    "EMPLOI",
    "REMOTE",
    "Remote (Worldwide)",
    "REMOTE",
    "Temps plein",
    "Tech & Digital",
    "SENIOR",
    ["Power Platform", "Azure", "AI"],
    5,
  ),
  o(
    "SEHIN GROUP",
    "Stagiaire Développeur",
    "STAGE",
    "CI",
    ABIDJAN,
    null,
    "Stage (6 mois)",
    "Tech & Digital",
    "BEGINNER",
    ["React", "Power Apps", "SharePoint"],
    7,
  ),
  o(
    "Upwork",
    "Développement d'une app métier",
    "FREELANCE",
    "REMOTE",
    "Remote",
    null,
    "Mission (1-3 mois)",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Power Apps", "API", "SQL"],
    1,
  ),
  o(
    "Banque Atlantique",
    "Consultant Data & BI",
    "PROJET",
    "CI",
    ABIDJAN,
    null,
    "Mission",
    "Data & IA",
    "INTERMEDIATE",
    ["Power BI", "Dataverse", "Data Analysis"],
    3,
  ),
  o(
    "Orange CI",
    "Product Owner Digital",
    "EMPLOI",
    "AFRICA",
    "Côte d'Ivoire / Afrique de l'Ouest",
    null,
    "CDI",
    "Gestion & Business",
    "SENIOR",
    ["Gestion de projet", "Agile", "Communication"],
    7,
    "Orange Digital Center",
  ),

  o(
    "AGL",
    "Chef de projet digital",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Gestion & Business",
    "SENIOR",
    ["Gestion de projet", "Agile", "Leadership"],
    9,
  ),
  o(
    "AGL",
    "Analyste Business Intelligence",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Data & IA",
    "INTERMEDIATE",
    ["Power BI", "SQL", "Data Analysis"],
    12,
  ),
  o(
    "AGL",
    "Consultant Dataverse",
    "PROJET",
    "CI",
    ABIDJAN,
    null,
    "Mission (3-6 mois)",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Dataverse", "Power Apps", "Power Automate"],
    14,
  ),
  o(
    "AGL",
    "Développeur Full Stack",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    ["React", "Node.js", "SQL"],
    15,
  ),
  o(
    "AGL",
    "Product Owner",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Gestion & Business",
    "SENIOR",
    ["Agile", "Gestion de projet", "Communication"],
    18,
  ),
  o(
    "AGL",
    "Data Engineer",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Data & IA",
    "SENIOR",
    ["Python", "SQL", "Azure"],
    20,
  ),
  o(
    "AGL",
    "Administrateur SharePoint",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDD",
    "Cloud & Infrastructure",
    "INTERMEDIATE",
    ["SharePoint", "Microsoft 365", "Power Automate"],
    22,
  ),
  o(
    "AGL",
    "Architecte de solutions",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "SENIOR",
    ["Azure", "Power Platform", "API"],
    25,
  ),
  o(
    "AGL",
    "Stagiaire Power Apps",
    "STAGE",
    "CI",
    ABIDJAN,
    null,
    "Stage (4 mois)",
    "Tech & Digital",
    "BEGINNER",
    ["Power Apps", "Dataverse"],
    26,
  ),
  o(
    "AGL",
    "Support applicatif niveau 2",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Cloud & Infrastructure",
    "BEGINNER",
    ["Support IT", "SQL", "Communication"],
    29,
  ),
  o(
    "AGL",
    "Formateur Power Platform",
    "FREELANCE",
    "CI",
    ABIDJAN,
    null,
    "Mission (1 mois)",
    "Tech & Digital",
    "SENIOR",
    ["Power Apps", "Power Automate", "Communication"],
    31,
  ),

  o(
    "Microsoft",
    "Cloud Solution Architect",
    "EMPLOI",
    "EUROPE",
    "Paris, France",
    "HYBRID",
    "Temps plein",
    "Cloud & Infrastructure",
    "SENIOR",
    ["Azure", "Cloud", "Architecture"],
    11,
  ),
  o(
    "Microsoft",
    "Customer Success Manager",
    "EMPLOI",
    "EUROPE",
    "Dublin, Irlande",
    "HYBRID",
    "Temps plein",
    "Gestion & Business",
    "INTERMEDIATE",
    ["Communication", "Power Platform", "Gestion de projet"],
    10,
  ),
  o(
    "Microsoft",
    "Technical Trainer Power Platform",
    "FREELANCE",
    "REMOTE",
    "Remote (Europe)",
    null,
    "Mission (1-3 mois)",
    "Tech & Digital",
    "SENIOR",
    ["Power Apps", "Power BI", "Communication"],
    13,
  ),
  o(
    "Microsoft",
    "Data & AI Specialist",
    "EMPLOI",
    "NORTH_AMERICA",
    "Redmond, États-Unis",
    "ONSITE",
    "Temps plein",
    "Data & IA",
    "SENIOR",
    ["AI", "Azure", "Python"],
    16,
  ),
  o(
    "Microsoft",
    "Program Manager Power Apps",
    "EMPLOI",
    "NORTH_AMERICA",
    "Seattle, États-Unis",
    "HYBRID",
    "Temps plein",
    "Gestion & Business",
    "SENIOR",
    ["Power Apps", "Gestion de projet", "Leadership"],
    19,
  ),
  o(
    "Microsoft",
    "Support Engineer Dynamics 365",
    "EMPLOI",
    "AFRICA",
    "Casablanca, Maroc",
    "ONSITE",
    "CDI",
    "Cloud & Infrastructure",
    "BEGINNER",
    ["Dynamics 365", "Support IT", "Dataverse"],
    21,
  ),
  o(
    "Microsoft",
    "Partner Development Manager",
    "EMPLOI",
    "AFRICA",
    "Johannesburg, Afrique du Sud",
    "HYBRID",
    "Temps plein",
    "Gestion & Business",
    "SENIOR",
    ["Communication", "Leadership", "Power Platform"],
    27,
  ),

  o(
    "Orange CI",
    "Développeur Power Platform",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Power Apps", "Power Automate", "Dataverse"],
    12,
    "Orange Digital Center",
  ),
  o(
    "Orange CI",
    "Data Analyst",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Data & IA",
    "INTERMEDIATE",
    ["Power BI", "SQL", "Python"],
    11,
  ),
  o(
    "Orange CI",
    "Chef de projet réseau",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Cloud & Infrastructure",
    "SENIOR",
    ["Réseau", "Gestion de projet", "Leadership"],
    17,
  ),
  o(
    "Orange CI",
    "Stagiaire Marketing digital",
    "STAGE",
    "CI",
    ABIDJAN,
    null,
    "Stage (6 mois)",
    "Autres",
    "BEGINNER",
    ["Communication", "Analyse fonctionnelle"],
    23,
  ),
  o(
    "Orange CI",
    "Ingénieur Cloud",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Cloud & Infrastructure",
    "INTERMEDIATE",
    ["Azure", "Cloud", "Réseau"],
    28,
  ),

  o(
    "SEHIN GROUP",
    "Analyste fonctionnel Power Platform",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Power Apps", "Analyse fonctionnelle", "Power Automate"],
    13,
  ),
  o(
    "SEHIN GROUP",
    "Consultant Power Automate",
    "PROJET",
    "CI",
    ABIDJAN,
    null,
    "Mission (2 mois)",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Power Automate", "SharePoint", "API"],
    12,
  ),
  o(
    "SEHIN GROUP",
    "Alternant Chef de projet",
    "ALTERNANCE",
    "CI",
    ABIDJAN,
    null,
    "Alternance (12 mois)",
    "Gestion & Business",
    "BEGINNER",
    ["Gestion de projet", "Agile", "Communication"],
    20,
  ),
  o(
    "SEHIN GROUP",
    "Designer UX/UI",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDD",
    "Autres",
    "INTERMEDIATE",
    ["Design", "UI/UX", "Communication"],
    30,
  ),

  o(
    "Banque Atlantique",
    "Analyste risques",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Gestion & Business",
    "INTERMEDIATE",
    ["Analyse fonctionnelle", "SQL", "Communication"],
    9,
  ),
  o(
    "Banque Atlantique",
    "Développeur Power Apps",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Power Apps", "Dataverse", "Power Automate"],
    15,
  ),
  o(
    "Banque Atlantique",
    "Chef de projet transformation digitale",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "ONSITE",
    "CDI",
    "Gestion & Business",
    "SENIOR",
    ["Gestion de projet", "Leadership", "Agile"],
    24,
  ),

  o(
    "TotalEnergies",
    "Développeur low-code",
    "EMPLOI",
    "CI",
    ABIDJAN,
    "HYBRID",
    "CDI",
    "Tech & Digital",
    "INTERMEDIATE",
    ["Power Apps", "Power Automate", "SharePoint"],
    14,
  ),
];

/** What a company says about itself, shown on each of its offers. */
const COMPANIES: Record<
  string,
  { legalName: string; sector: string; size: string; tagline: string; about: string; website: string }
> = {
  AGL: {
    legalName: "Africa Global Logistics",
    sector: "Logistique & Transport",
    size: "Plus de 10 000 employés",
    tagline: "Connecting Africa\nEmpowering tomorrow",
    about:
      "AGL est un opérateur logistique de référence en Afrique, présent dans plus de 40 pays. Nous proposons des solutions intégrées de transport, logistique et supply chain pour soutenir la croissance du continent.",
    website: "https://www.agl-group.com",
  },
  Microsoft: {
    legalName: "Microsoft",
    sector: "Logiciels & Cloud",
    size: "Plus de 200 000 employés",
    tagline: "Empower every person\nand every organization",
    about:
      "Microsoft accompagne les organisations du monde entier dans leur transformation numérique grâce au cloud, à l'intelligence artificielle et à la Power Platform.",
    website: "https://www.microsoft.com",
  },
  "Orange CI": {
    legalName: "Orange Côte d'Ivoire",
    sector: "Télécommunications",
    size: "Plus de 2 000 employés",
    tagline: "Le digital au service\nde chacun",
    about:
      "Orange Côte d'Ivoire est l'un des principaux opérateurs télécoms du pays et investit dans l'innovation, la fintech et la formation au numérique.",
    website: "https://www.orange.ci",
  },
  "SEHIN GROUP": {
    legalName: "SEHIN GROUP",
    sector: "Conseil & Transformation digitale",
    size: "50 à 200 employés",
    tagline: "Your skills.\nYour future.",
    about:
      "SEHIN GROUP accompagne les entreprises africaines dans leur transformation digitale : solutions Power Platform, data et formation des équipes.",
    website: "https://skillpass.example/sehin-group",
  },
  "Banque Atlantique": {
    legalName: "Banque Atlantique Côte d'Ivoire",
    sector: "Banque & Finance",
    size: "Plus de 1 000 employés",
    tagline: "La banque qui\nvous ressemble",
    about:
      "Banque Atlantique est un acteur bancaire majeur d'Afrique de l'Ouest qui modernise ses services grâce au digital et à la donnée.",
    website: "https://www.banqueatlantique.net",
  },
  Upwork: {
    legalName: "Upwork",
    sector: "Plateforme freelance",
    size: "Plus de 800 employés",
    tagline: "Work without limits",
    about:
      "Upwork met en relation des entreprises et des freelances du monde entier pour des missions à distance.",
    website: "https://www.upwork.com",
  },
  TotalEnergies: {
    legalName: "TotalEnergies",
    sector: "Énergie",
    size: "Plus de 100 000 employés",
    tagline: "Energy for all",
    about:
      "TotalEnergies est une compagnie multi-énergies mondiale qui investit dans la digitalisation de ses opérations.",
    website: "https://totalenergies.com",
  },
};

const DAY_MS = 86_400_000;

/** Stable pseudo-random number in [min, max] from a string, so demo figures never jump between reloads. */
const spread = (seed: string, min: number, max: number) =>
  min + ([...seed].reduce((sum, ch) => (sum * 31 + ch.charCodeAt(0)) % 9973, 7) % (max - min + 1));

const WORK_MODE_DETAIL: Record<string, string> = {
  HYBRID: "Hybride (2-3 jours sur site)",
  ONSITE: "Sur site",
  REMOTE: "Télétravail complet",
};
const EXPERIENCE: Record<string, string> = {
  BEGINNER: "Débutant accepté",
  INTERMEDIATE: "Intermédiaire",
  SENIOR: "Senior",
};

/** Hand-written content for the offer shown on the detail mockup. */
const FEATURED = {
  title: "Développeur Power Platform",
  company: "AGL",
  description:
    "Nous recherchons un Développeur Power Platform passionné et expérimenté pour rejoindre notre équipe Digital & Innovation. Vous serez en charge de concevoir, développer et déployer des solutions métiers avec Microsoft Power Platform (Power Apps, Power Automate, Power BI, Dataverse) afin d'optimiser nos processus et accompagner la transformation digitale du groupe.",
  missions: [
    "Analyser les besoins métiers et proposer des solutions adaptées avec Power Platform.",
    "Développer des applications Canvas et Model-driven Apps.",
    "Créer et automatiser des processus avec Power Automate.",
    "Concevoir des rapports et tableaux de bord avec Power BI.",
    "Assurer l'intégration avec les systèmes existants (SharePoint, Dataverse, APIs).",
    "Accompagner les utilisateurs et assurer la formation.",
    "Participer à la gouvernance et aux bonnes pratiques de la plateforme.",
  ],
  optionalSkills: ["Azure"],
  experienceRange: "Intermédiaire / Senior",
  views: 245,
  applicants: 32,
};

function sheet(s: Seed, now: Date): Omit<OpportunityDTO, "id"> {
  const { daysAgo, companyLabel, ...base } = s;
  const featured = base.company === FEATURED.company && base.title === FEATURED.title;
  const company = COMPANIES[base.company];
  const main = base.skills.slice(0, 3).join(", ");
  const key = `${base.company}|${base.title}`;
  const publishedAt = new Date(now.getTime() - daysAgo * DAY_MS);

  const description = featured
    ? FEATURED.description
    : `${companyLabel ?? base.company} recherche un(e) ${base.title} (${base.location}) pour rejoindre ses équipes. ` +
      `Vous interviendrez sur des sujets liés à ${main}, au sein d'une équipe pluridisciplinaire, avec des objectifs clairs et un vrai impact sur les utilisateurs.`;

  return {
    ...base,
    companyLabel: companyLabel ?? null,
    description,
    applyUrl: null,
    publishedAt: publishedAt.toISOString(),
    deadline: new Date(publishedAt.getTime() + 28 * DAY_MS).toISOString(),
    views: featured ? FEATURED.views : spread(key, 40, 600),
    applicants: featured ? FEATURED.applicants : spread(`${key}#`, 4, 60),
    workModeDetail: base.workMode ? (WORK_MODE_DETAIL[base.workMode] ?? null) : null,
    experienceRange: featured ? FEATURED.experienceRange : (EXPERIENCE[base.level] ?? null),
    salary: base.kind === "STAGE" ? "Gratification selon la grille en vigueur" : "À discuter",
    missions: featured
      ? FEATURED.missions
      : [
          "Analyser les besoins et proposer des solutions adaptées.",
          `Concevoir et mettre en œuvre avec ${main}.`,
          "Assurer la qualité, les tests et la documentation.",
          "Collaborer avec les équipes métiers et techniques.",
          "Partager les bonnes pratiques et accompagner les utilisateurs.",
        ],
    requirements: [
      `${EXPERIENCE[base.level] ?? "Expérience adaptée"} sur un poste proche.`,
      `Maîtrise de ${main}.`,
      "Autonomie, rigueur et sens du service.",
      "Esprit d'équipe et bonne communication.",
      "Français courant ; anglais professionnel apprécié.",
    ],
    perks: [
      "Assurance santé",
      "Formation et certifications financées",
      ...(base.workMode === "HYBRID" || base.workMode === "REMOTE" ? ["Télétravail partiel ou complet"] : []),
      "Environnement de travail moderne",
      "Perspectives d'évolution",
      "Prime de performance",
    ],
    process: [
      "Candidature en ligne",
      "Entretien téléphonique (30 min)",
      "Entretien technique",
      "Rencontre avec l'équipe",
      "Proposition et intégration",
    ],
    optionalSkills: featured ? FEATURED.optionalSkills : [],
    companyLegalName: company?.legalName ?? base.company,
    companySector: company?.sector ?? null,
    companySize: company?.size ?? null,
    companyAbout: company?.about ?? null,
    companyTagline: company?.tagline ?? null,
    companyVerified: Boolean(company),
    companyWebsite: company?.website ?? null,
  };
}

/** Offers with publication dates relative to `now`, so "il y a 2 jours" stays true whenever the demo runs. */
export function buildDemoOpportunities(now = new Date()): Omit<OpportunityDTO, "id">[] {
  return SEEDS.map((s) => sheet(s, now));
}
