/** Suggestions offered when writing an offer. Free entries are always possible. */
export const TECH_SKILLS = [
  "Power Apps",
  "Power Automate",
  "Power BI",
  "Dataverse",
  "SharePoint",
  "Azure",
  "Microsoft 365",
  "SQL",
  "DAX",
  "Power Fx",
  "API",
  "Git",
  "JavaScript",
  "TypeScript",
  "React",
  "Node.js",
  "Python",
  "C#",
  ".NET",
  "Java",
  "Docker",
  "CI/CD",
  "DevOps",
  "Excel",
  "Data Analysis",
  "Machine Learning",
  "Cybersécurité",
  "Réseaux",
  "Linux",
  "Dynamics 365",
  "Salesforce",
  "Gestion de projet",
  "Agilité",
  "Scrum",
  "ALM",
  "UX/UI",
  "Analyse fonctionnelle",
  "Supply Chain",
  "Comptabilité",
] as const;

export const SUGGESTED_TECH_SKILLS = [
  "SharePoint",
  "Azure",
  "Microsoft 365",
  "SQL",
  "DAX",
  "Power Fx",
  "API",
  "Git",
];

export const SOFT_SKILLS = [
  "Esprit d'analyse",
  "Autonomie",
  "Esprit d'équipe",
  "Communication",
  "Leadership",
  "Rigueur",
  "Adaptabilité",
  "Créativité",
  "Gestion du temps",
  "Sens du service",
  "Résolution de problèmes",
  "Négociation",
] as const;

export const CERTIFICATIONS = [
  "PL-200",
  "PL-300",
  "PL-400",
  "PL-900",
  "AZ-900",
  "AZ-104",
  "MS-102",
  "Microsoft 365",
  "AWS Certified Solutions Architect",
  "Google Cloud Professional",
  "Scrum Master",
  "PMP",
  "ITIL 4 Foundation",
  "CISSP",
] as const;

export const LANGUAGE_OPTIONS = ["Français", "Anglais"] as const;
